import os


EMBEDDING_MODEL_NAME = os.getenv("EMBEDDING_MODEL_NAME", "sentence-transformers/all-MiniLM-L6-v2")
WHISPER_MODEL_SIZE = os.getenv("WHISPER_MODEL_SIZE", "base")
WHISPER_COMPUTE_TYPE = os.getenv("WHISPER_COMPUTE_TYPE", "int8")
VISION_IMAGE_WEIGHT = float(os.getenv("VISION_IMAGE_WEIGHT", "0.38"))
TEXT_CONFIDENCE_THRESHOLD = float(os.getenv("TEXT_CONFIDENCE_THRESHOLD", "0.26"))
CONTEXT_REPEAT_HIGH = int(os.getenv("CONTEXT_REPEAT_HIGH", "5"))
CONTEXT_REPEAT_MEDIUM = int(os.getenv("CONTEXT_REPEAT_MEDIUM", "3"))
MAX_EXPLANATION_KEYWORDS = int(os.getenv("MAX_EXPLANATION_KEYWORDS", "4"))

