COMPLAINT_CATEGORIES = [
    {
        "id": "plumbing",
        "label": "Plumbing",
        "aliases": [
            "water leakage",
            "pipe burst",
            "burst pipe",
            "leakage",
            "seepage",
            "tap leak",
            "overflowing tank",
            "water line damage",
        ],
        "keywords": [
            ("water leakage", 1.0),
            ("pipe burst", 1.0),
            ("burst pipe", 1.0),
            ("water leak", 0.92),
            ("pipe leak", 0.92),
            ("leakage", 0.7),
            ("seepage", 0.68),
            ("wet wall", 0.58),
            ("tank overflow", 0.88),
            ("tap leak", 0.72),
        ],
        "critical_keywords": ["electrical panel", "short circuit", "transformer", "exposed wire"],
        "color_hint": "blue",
    },
    {
        "id": "electrical",
        "label": "Electrical",
        "aliases": [
            "power outage",
            "streetlight not working",
            "street light off",
            "live wire",
            "hanging wire",
            "electrical fault",
            "transformer issue",
        ],
        "keywords": [
            ("power outage", 1.0),
            ("streetlight not working", 1.0),
            ("street light off", 1.0),
            ("electrical panel", 0.96),
            ("live wire", 1.0),
            ("hanging wire", 0.9),
            ("snapped wire", 0.96),
            ("transformer", 0.84),
            ("no power", 0.82),
            ("no light", 0.78),
            ("short circuit", 0.98),
        ],
        "critical_keywords": ["fire", "spark", "smoke", "electrical panel", "transformer"],
        "color_hint": "red",
    },
    {
        "id": "road_damage",
        "label": "Road Damage",
        "aliases": [
            "pothole",
            "road crack",
            "damaged road",
            "sinkhole",
            "cave in",
            "road collapse",
        ],
        "keywords": [
            ("pothole", 1.0),
            ("road crack", 0.94),
            ("damaged road", 0.9),
            ("broken road", 0.92),
            ("sinkhole", 1.0),
            ("cave in", 0.94),
            ("road collapse", 0.96),
            ("crater", 0.7),
        ],
        "critical_keywords": ["ambulance route", "school bus", "main road"],
        "color_hint": "neutral",
    },
    {
        "id": "garbage",
        "label": "Garbage",
        "aliases": ["garbage overflow", "trash pile", "waste dump", "litter accumulation"],
        "keywords": [
            ("garbage", 1.0),
            ("trash", 0.82),
            ("waste", 0.76),
            ("overflowing bin", 0.9),
            ("dump", 0.84),
            ("litter", 0.7),
            ("unclean", 0.48),
        ],
        "critical_keywords": ["hospital", "school", "food area"],
        "color_hint": "green",
    },
    {
        "id": "waterlogging",
        "label": "Waterlogging",
        "aliases": ["drainage issue", "water logging", "stagnant water", "flooded street"],
        "keywords": [
            ("water logging", 1.0),
            ("waterlogged", 1.0),
            ("water stagnation", 0.92),
            ("stagnant water", 0.92),
            ("blocked drainage", 0.94),
            ("drain overflow", 0.88),
            ("flooded street", 0.9),
        ],
        "critical_keywords": ["mosquito", "hospital", "school"],
        "color_hint": "blue",
    },
    {
        "id": "fire_hazard",
        "label": "Fire Hazard",
        "aliases": ["fire", "smoke", "gas leak", "burning wire", "sparking"],
        "keywords": [
            ("fire", 1.0),
            ("smoke", 0.9),
            ("gas leak", 1.0),
            ("burning wire", 1.0),
            ("sparking", 0.84),
            ("flame", 0.92),
            ("explosion", 1.0),
        ],
        "critical_keywords": ["gas leak", "explosion", "people trapped", "hospital"],
        "color_hint": "red",
    },
    {
        "id": "structural_damage",
        "label": "Structural Damage",
        "aliases": ["wall crack", "ceiling crack", "building damage", "plaster fallen"],
        "keywords": [
            ("wall crack", 1.0),
            ("ceiling crack", 0.96),
            ("building crack", 1.0),
            ("plaster fallen", 0.82),
            ("collapse", 0.9),
            ("damaged wall", 0.84),
        ],
        "critical_keywords": ["collapse", "people inside", "school building"],
        "color_hint": "neutral",
    },
]

FAQ_HINTS = {
    "login": "Use the login/register overlay to authenticate as Citizen or Admin.",
    "report": "Use Report an Issue to submit text, voice, and image-based complaints.",
    "status": "Use My Complaints or ask the chatbot for your latest complaint status.",
    "map": "Use the live location preview in the map panel to verify the issue location.",
}

